### ISSUE TITLE
specify custom m2 repo

### ISSUE THREAD

**Issue by mbjelac** [olhtbr/maven-cache-resource#1]
It would be nice to be able to specify a custom maven repository, if such is available (e.g. a privately hosted Artifactory).

**Comment by olhtbr** [comment]
Good idea. I'm thinking of adding source configuration options to specify [mirrors](https://maven.apache.org/settings.html#Mirrors) and corresponding [servers](https://maven.apache.org/settings.html#Servers) for credentials.

**Comment by mbjelac** [comment]
I'm already using a custom settings.xml for my other maven commands. Could this file just be reused for your resource?

**Comment by olhtbr** [comment]
Sorry, I was quite busy this week. Reusing a file makes much more sense :) I'll put in an argument today, so one can pass the settings.xml file to the get step from another resource (eg. a git resource).

**Comment by mbjelac** [comment]
Yes, that would be great! I don't know if you can pass resources to resources... But that would be ideal: Specify resource and file path inside the resource.

**Comment by olhtbr** [comment]
Turns out it's only possible, when doing a put. I created a 1.0.1 release to keep the current version and started to refactor it to support passing in the source code and settings from other resources.

It would work something like this:
```yaml
- get: settings-repo
- get: source-repo
- put: cache
  params:
    pom: source-repo/pom.xml
    global_settings: settings-repo/settings.xml
    security_settings: settings-repo/settings-security.xml
```

You could then use the `cache` resource as input to other tasks, just like before. At least that is the theory :)

**Comment by mbjelac** [comment]
Just make sure you disable pushing to remote repo (if you're using the git resource for this).

**Comment by olhtbr** [comment]
After trying to figure this out for a couple of days, it seems it's not an approach that would work in concourse.

Only get steps save the state of the resource, ie. dependencies must be downloaded in the get step. This state then can be passed to task and put steps, but not other get steps. So a settings.xml file downloaded with another resource can't be passed to the get step of the maven cache resource (only to a put step, but then the downloaded dependencies can't be passed to other steps).

So I fall back to the simplest implementation at this point, ie. adding support for a settings.xml URL in the source configuration, like this:

```yaml
resources:
  - name: maven-cache
    type: maven-cache # Defined in resource_types
    source:
      # Git related config here...
      # Maven settings.xml url
      settings:
          url: http://example.com/settings.xml
      # Encrypted maven master password
      master-password: {someencryptedmasterpassword}
```

The file is downloaded by wget and used during caching. If encryption is used for credentials, the master password can also be passed to the resource with the `master-password` parameter.

The changes are included in v1.1.0. Let me know if this could be improved more :)
